name: cde_core
description: Low-level, core functionality for the Chrome Dev Editor (CDE).
version: 0.0.1-dev
author: The Chrome Dev Editor team
homepage: https://github.com/dart-lang/chromedeveditor/
environment:
  sdk: '>=1.0.0 <2.0.0'
dev_dependencies:
  unittest: any
